/**
 * Single entry point for ledger appends. Call sites that previously did
 *   db.insert(balanceLedger).values({ ... })
 * now call
 *   appendLedgerEntry({ ... })
 * which seals the chain fields before the row becomes visible.
 *
 * On any chain error (previous hash lookup, signing) the append throws and
 * the caller MUST fail closed — never write an unsigned row.
 *
 * Adapted to worktree-p2's persistence layer:
 *   - db + schema imported from ../db/client.js (not ../db/index.js)
 *   - ledger table is schema.balanceLedger with bigint identity PK, numeric
 *     amount, runId (not jobId), reason (not description), currency
 *
 * Two-phase insert: the bigint identity PK is generated by Postgres on
 * INSERT, so it cannot be known when we seal the payload. We resolve this by
 * signing with `id = String(row.id)`:
 *   1. INSERT the row with NULL chain fields inside a transaction.
 *   2. Read back the generated id.
 *   3. Seal the payload using that id; the payload hash now binds the PK.
 *   4. UPDATE the row with prevHash/payloadHash/signature/signerPublicKey.
 *   5. COMMIT. Until commit, no other reader sees a partially-signed row.
 *
 * Audit reconstruction is exact: `id = String(row.id)` is deterministically
 * re-derivable from the row itself, so the chain walk recomputes the same
 * canonical blob that was signed.
 */

import { eq, desc, sql } from "drizzle-orm"
import { db, schema } from "../db/client.js"
import {
  GENESIS_HASH,
  sealEntry,
  hashLink,
  type LedgerPayload,
} from "./chain.js"

export interface NewLedgerEntryInput {
  workspaceId: string
  amount: number
  type: "topup" | "charge" | "refund"
  currency?: string
  reason?: string | null
  runId?: string | null
}

/**
 * Fetch the chain head for a workspace: hashLink(prevHash, payloadHash) of
 * the most recent row that actually carries chain fields. Rows with NULL
 * chain fields (pre-migration history) are treated as genesis — we walk
 * past them and return GENESIS_HASH only if no signed row exists. This keeps
 * the chain well-defined even when the migration lands on a non-empty table.
 *
 * Ordering: DESC on the bigint identity PK, take first. The identity column
 * is monotonic, so this is the strict, collision-free order. createdAt alone
 * is not strict under simultaneous inserts; a future v2 adds a per-workspace
 * sequence column with a unique constraint.
 */
async function chainHeadHash(workspaceId: string): Promise<string> {
  const rows = await db
    .select({
      payloadHash: schema.balanceLedger.payloadHash,
      prevHash: schema.balanceLedger.prevHash,
    })
    .from(schema.balanceLedger)
    .where(
      sql`${schema.balanceLedger.workspaceId} = ${workspaceId}
          AND ${schema.balanceLedger.payloadHash} IS NOT NULL`,
    )
    .orderBy(desc(schema.balanceLedger.id))
    .limit(1)
  if (rows.length === 0) return GENESIS_HASH
  const last = rows[0]
  return hashLink(last.prevHash!, last.payloadHash!)
}

export async function appendLedgerEntry(
  input: NewLedgerEntryInput,
): Promise<void> {
  const amountStr = input.amount.toFixed(4)
  const currency = input.currency ?? "USD"

  await db.transaction(async (tx) => {
    // 1. Insert with NULL chain fields; let Postgres assign the identity PK.
    const inserted = await tx
      .insert(schema.balanceLedger)
      .values({
        workspaceId: input.workspaceId,
        runId: input.runId ?? null,
        type: input.type,
        amount: amountStr,
        currency,
        reason: input.reason ?? null,
        // chain fields intentionally null; filled in step 3
      })
      .returning({ id: schema.balanceLedger.id })

    const rowId = inserted[0]?.id
    if (rowId === undefined) {
      throw new Error(
        `appendLedgerEntry: insert returned no id for workspace ${input.workspaceId}`,
      )
    }

    // 2. Build the canonical payload using the DB-assigned id. The id is
    //    part of the signed blob, binding the signature to this exact row.
    const createdAtDate = new Date()
    const payload: LedgerPayload = {
      id: String(rowId),
      workspaceId: input.workspaceId,
      amount: amountStr,
      type: input.type,
      currency,
      reason: input.reason ?? null,
      runId: input.runId ?? null,
      createdAt: createdAtDate.toISOString(),
    }

    // 3. Seal: sign payloadHash with the process Ed25519 key, chaining off
    //    the current head. NOTE: chainHeadHash queries outside the tx because
    //    the signing key + head computation do not need tx isolation — the
    //    hash-link invariants are established at COMMIT by the row lock the
    //    UPDATE takes. For strict serializability under high concurrency a
    //    per-workspace advisory lock would be added here; v1 traffic is
    //    single-writer-per-workspace.
    const prevHash = await chainHeadHash(input.workspaceId)
    const entry = await sealEntry(payload, prevHash)

    // 4. Update the row with the chain fields. The createdAt is also pinned
    //    to the same timestamp used in the payload so audit reconstruction
    //    byte-matches.
    await tx
      .update(schema.balanceLedger)
      .set({
        createdAt: createdAtDate,
        prevHash: entry.prevHash,
        payloadHash: entry.payloadHash,
        signatureAlgo: entry.signatureAlgo,
        signature: entry.signature,
        signerPublicKey: entry.signerPublicKey,
      })
      .where(eq(schema.balanceLedger.id, rowId))
  })
}
